name: E2E Tests

on:
  workflow_dispatch:

jobs:
  E2E_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '20'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn test -DbrowserType="chrome" -DheadlessExecution="true" -Dtest="tests.newUserSignUpTest"

      - name: Publish Report
        uses: dorny/test-reporter@v1
        if: always()   
        with:
          name: Tests Report            
          path: 'target/surefire-reports/TEST-*.xml'    
          reporter: java-junit

     # - name: Publish JUnit Reports
      #  uses: actions/upload-artifact@v2
       # with:
        #  name: junit-reports
         # path: target/surefire-reports/ 
