name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''

jobs:
  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn test -DbrowserType="chrome" -DheadlessExecution="true" -Dtest="${{ github.event.inputs.testsPath }}"

  E2E_Firefox_Windows_Test:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn test -DbrowserType="firefox" -DheadlessExecution="false"  -Dtest="${{ github.event.inputs.testsPath }}"

  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests on Edge
        continue-on-error: true
        run: mvn test -DbrowserType="edge" -DheadlessExecution="false"  -Dtest="${{ github.event.inputs.testsPath }}"

     # - name: Publish JUnit Reports
      #  uses: actions/upload-artifact@v2
       # with:
        #  name: junit-reports
         # path: target/surefire-reports/ 

        #- name: Publish Report
        #uses: dorny/test-reporter@v1
        #if: always()   
        #with:
         # name: Tests Report            
          #path: 'target/surefire-reports/TEST-*.xml'    
          #reporter: java-junit
